analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - macos/**
    - linux/**
    - web/**
    - windows/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_key_in_widget_constructors: true
